on:
  push:
    branches:
      - master
jobs:
  build_push_sample_app_image:
    name: Build and Push Sample App docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create a directory
        run: mkdir sample-apps/http-server/aws-xray-sdk-go

      - name: Copy X-Ray SDK to deployment package with Sample App
        run: rsync -r * sample-apps/http-server/aws-xray-sdk-go --exclude sample-apps/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layer
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}

      - name: Login to ECR
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.AWS_REGISTRY_ACCOUNT_ID }}.dkr.ecr.us-west-2.amazonaws.com
          username: ${{ secrets.INTEG_TEST_AWS_KEY_ID }}
          password: ${{ secrets.INTEG_TEST_AWS_KEY_SECRET }}

      - name: Build image and push to ECR
        uses: docker/build-push-action@v2
        with:
          file: sample-apps/http-server/Dockerfile
          context: .
          tags: 611364707713.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-otel-goxray-sample-app:${{ github.sha }}
          push: true
